/// <reference path="../../typings/index.d.ts"/>
/// <reference path="../config/scene.ts"/>
/// <reference path="../objects/asset/asset.ts"/>
/// <reference path="../objects/button/button.ts"/>
/// <reference path="../objects/label/label.ts"/>
/// <reference path="../objects/bubbles/bubble.ts" />
/// <reference path="../objects/vector2/vector2.ts" />
/// <reference path="../objects/gameobject/gameobject.ts" />
/// <reference path="../objects/scene/scene.ts"/>
/// <reference path="../objects/ocean/ocean.ts"/>
/// <reference path="../objects/island/island.ts"/>
/// <reference path="../objects/player/player.ts"/>
/// <reference path="../objects/shark/shark.ts"/>
/// <reference path="../managers/collision.ts" />
/// <reference path="../objects/treasure/treasure.js" />
/// <reference path="../scenes/over/over.ts"/>
/// <reference path="../scenes/play/play.ts"/>
/// <reference path="../scenes/menu/menu.ts"/>
/// <reference path="../scenes/instructions/instructions.ts"/> 
//# sourceMappingURL=_reference.js.map